---
spring:
    profiles: default
    resources:
        static-locations: "file:./app"

management:
    endpoints:
        web:
            exposure:
                include: "*"
cds:
    security:
        authenticate-unknown-endpoints: false
    odata-v4:
        endpoint:
            path: "/"
---
spring:
    profiles: cloud
management:
    endpoints:
        web:
            exposure:
                include: "*"
